<template>
  <div class="social-icons">
    <a
      class="social-icons-link"
      href="https://www.instagram.com/clubquarantaene/"
      target="_blank"
    >
      Instagram
    </a>
    •
    <a
      class="social-icons-link"
      href="https://www.youtube.com/residentadvisor"
      target="_blank"
    >
      YouTube
    </a>
    •
    <a
      class="social-icons-link"
      href="https://steadyhq.com/en/clubquarantaene"
      target="_blank"
    >
      Steady
    </a>
    •
    <a
      class="social-icons-link"
      href="https://shop.clubquarantaene.stream"
      target="_blank"
    >
      Shop
    </a>
    •
    <nuxt-link class="social-icons-link" to="imprint">
      Imprint
    </nuxt-link>
  </div>
</template>
